[package]
name = "greenthumb_contracts"
version = "0.1.0"
edition = "2021"

[dependencies]
solana-program = "1.10.32"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
bincode = "1.3"

